[package]
name = "test-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "5.0.0", features = ["legacy"] }
borsh = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

